name: ✅ Integration tester
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Integration test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kotlin-version: [ 1.9.22 ]
        java-version: [ 21 ]

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21 and Kotlin 1.9.22
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
          kotlin-version: ${{ matrix.kotlin-version }}

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        run: ./gradlew clean test
